/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Reactive "Siri-style" waveform face — baked-EAF implementation.
 *
 * Drop-in replacement for waveform.c. Same public symbols (emote_face_init,
 * emote_face_set_state, emote_face_set_synthetic_amplitude,
 * emote_face_set_amplitude_source) so emote.c (calls emote_face_init at
 * emote.c:281) and app_claw_face_bridge.c need NO changes.
 *
 * WHY THIS, NOT waveform.c: this engine (espressif2022/esp_emote_gfx, vendored
 * in the build clone) has NO canvas widget. A runtime CPU-drawn RGB565A8 buffer
 * pushed via gfx_img_set_src renders as a skewed spiral / white on this CO5300
 * panel (proven empirically — even a 64x64 solid square spiraled). The only
 * sanctioned reactive lever is the BAKED gfx_anim widget. gfx_motion is NOT
 * shipped in this engine version (no include/widget/gfx_motion.h), so affine
 * transforms are off the table too.
 *
 * APPROACH: one custom gfx_anim object ("rwave"), four baked looping EAFs (idle/
 * listen/think/speak, generated by firmware/mascot/gen_reactive_face.py, mounted
 * in the `emote` asset partition next to the eye emojis). The reactive states map
 * the live 0..1000 amplitude to the looping segment END frame, so a louder voice
 * plays deeper into a pre-baked "amplitude ramp" and the waveform visibly grows.
 *
 * CRITICAL — single-frame pinning does NOT work on this engine. The anim timer
 * (gfx_anim.c:824) only DRAWS a frame in the `current_frame < end_frame` branch;
 * with start==end it resets without drawing. So we always loop [0..end] with
 * end>=1 (it traverses intermediate frames and keeps drawing). See plan §2.
 *
 * Engine API used (all verified in the clone, file:line):
 *   emote_create_obj_by_type(h, "anim", name)  emote_api.h  (-> gfx_anim_create, emote_setup.c:245)
 *   emote_get_asset_data_by_name(h, name, &d, &n)  emote_assets.h:89
 *   gfx_anim_set_src(obj, data, len)            gfx_anim.h:45
 *   gfx_anim_set_segment(obj, start, end, fps, repeat)  gfx_anim.h:56  (clamps end, gfx_anim.c:1005)
 *   gfx_anim_start(obj) / gfx_anim_stop(obj)    gfx_anim.h:63 / :70
 *   gfx_obj_align(obj, GFX_ALIGN_CENTER, 0, 0)  core/gfx_obj.h
 *   emote_set_obj_visible / emote_set_anim_visible / emote_lock / emote_unlock  emote_api.h
 *
 * See docs/REACTIVE_FACE_PLAN.md for the full design + open questions.
 */

#include "emote.h"   /* public face API: emote_face_state_t + emote_face_* (in include/) */

#include <stdint.h>
#include <string.h>

#include "esp_check.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "gfx.h"   /* pulls in widget/gfx_anim.h + core/gfx_obj.h */
#include "expression_emote.h"
#include "display_arbiter.h"

static const char *TAG = "app_rwave";

/* Custom gfx object name (must not collide with predefined emote elem names). */
#define RWAVE_OBJ_NAME    "rwave"

/* Baked-asset file names — HARD CONTRACT with gen_reactive_face.py's STATE_ORDER
 * and with the `emote` partition manifest the orchestrator must populate. */
#define RWAVE_ASSET_IDLE    "rwave_idle.eaf"
#define RWAVE_ASSET_LISTEN  "rwave_listen.eaf"
#define RWAVE_ASSET_THINK   "rwave_think.eaf"
#define RWAVE_ASSET_SPEAK   "rwave_speak.eaf"

/* Per-state loop rate, applied via gfx_anim_set_segment() below. NOTE: the
 * loop/fps fields in assets_local/284_240/emote.json are NOT load-bearing for
 * THIS custom anim object — those are only read by emote_set_anim_emoji (the eye
 * flow, emote_op.c:287). This object sets its own fps here. The manifest fps
 * values mirror these for documentation, but THESE constants are authoritative.
 * Reactive states run a touch faster for livelier shimmer. */
#define RWAVE_FPS_IDLE      20
#define RWAVE_FPS_REACTIVE  24
#define RWAVE_FPS_THINK     24

/* Amplitude driver task cadence (Hz) and lerp for fluid attack/decay. */
#define RWAVE_DRIVER_HZ     20
#define RWAVE_DRIVER_MS     (1000 / RWAVE_DRIVER_HZ)
#define RWAVE_LERP          0.30f   /* eased displayed level toward target */

/* One baked EAF held resident in memory for its object's lifetime. The decoder
 * keeps the pointer (it does NOT copy — cf. eye's emote_acquire_data,
 * emote_op.c:283), so these blobs must stay valid while shown. They are mmap'd
 * read-only out of the asset partition; we just cache the pointer + frame count. */
typedef struct {
    const uint8_t *data;
    size_t         size;
    uint32_t       frames;   /* total frames INCLUDING the trailing _C sentinel */
    uint32_t       last;     /* max `end` for set_segment: the loop draws [0..end-1],
                              * so end == frames-1 is needed to display the highest
                              * real frame (index frames-2). The _C sentinel sits at
                              * frames-1 and is never prepared (timer resets without
                              * drawing on cf >= end_frame), so this cap is safe. */
    bool           loaded;
} rwave_clip_t;

typedef struct {
    emote_handle_t      emote;
    gfx_obj_t          *obj;          /* the custom "rwave" gfx_anim object */
    rwave_clip_t        idle, listen, think, speak;

    TaskHandle_t        task;
    volatile bool       run;
    volatile emote_face_state_t state;
    volatile int        synth_amp;    /* -1 = use live cb; else 0..1000 */
    emote_face_amp_cb_t amp_cb;

    float               disp_amp;     /* eased displayed amplitude 0..1 */
    int                 last_end;     /* last segment end issued (avoid churn) */
    const rwave_clip_t *cur_clip;     /* clip whose src is currently set */
} rwave_ctx_t;

static rwave_ctx_t s_rw;

/* ---- asset loading -------------------------------------------------------- */

/* Read the EAF header's frame-count field (offset 4, int32 LE) per the format in
 * gfx_eaf_dec.h:34 — the count INCLUDES the trailing _C sentinel frame, so the
 * last drawable frame index is (count - 2). We avoid eaf_init() here (internal
 * decoder API) and read the count straight from the header, which is stable. */
static uint32_t rwave_eaf_frame_count(const uint8_t *d, size_t n)
{
    /* Mirror eaf_init's validation (gfx_eaf_dec.c:724): byte 0 = 0x89,
     * bytes 1..3 = "EAF" or "AAF", frame count = int32 LE at offset 4. The count
     * INCLUDES the trailing _C sentinel frame. */
    if (!d || n < 8 || d[0] != 0x89) {
        return 0;
    }
    if (memcmp(d + 1, "EAF", 3) != 0 && memcmp(d + 1, "AAF", 3) != 0) {
        return 0;
    }
    int32_t total;
    memcpy(&total, d + 4, sizeof(total));    /* little-endian int32 */
    return total > 0 ? (uint32_t)total : 0;
}

static esp_err_t rwave_load_clip(const char *name, rwave_clip_t *clip)
{
    const uint8_t *data = NULL;
    size_t size = 0;
    esp_err_t err = emote_get_asset_data_by_name(s_rw.emote, name, &data, &size);
    if (err != ESP_OK || !data || size < 16) {
        ESP_LOGW(TAG, "asset '%s' not found (%s) — state will be skipped",
                 name, esp_err_to_name(err));
        clip->loaded = false;
        return err == ESP_OK ? ESP_ERR_NOT_FOUND : err;
    }
    /* Defensive: a malformed/mispacked asset-table entry can hand back a
     * non-mapped pointer (observed: an offset-like 0x001f9xxx value) with a
     * plausible size, and dereferencing it faults (LoadProhibited -> boot loop).
     * Every valid mmap'd-flash / SRAM / PSRAM data pointer on ESP32-S3 lives in
     * the cache window 0x3C000000..0x3FFFFFFF, so reject anything outside it and
     * fall back to the baked eye instead of crashing. */
    if ((uintptr_t)data < 0x3C000000UL || (uintptr_t)data >= 0x40000000UL) {
        ESP_LOGW(TAG, "asset '%s' resolved to non-mapped ptr %p — skipping (eye fallback)",
                 name, (const void *)data);
        clip->loaded = false;
        return ESP_ERR_INVALID_RESPONSE;
    }
    uint32_t total = rwave_eaf_frame_count(data, size);
    if (total < 2) {
        ESP_LOGW(TAG, "asset '%s' has too few frames (%u)", name, (unsigned)total);
        clip->loaded = false;
        return ESP_ERR_INVALID_SIZE;
    }
    clip->data = data;
    clip->size = size;
    clip->frames = total;
    clip->last = total - 1;          /* max set_segment end (exclusive draw window) */
    clip->loaded = true;
    ESP_LOGI(TAG, "loaded '%s' (%u B, %u real frames)", name,
             (unsigned)size, (unsigned)(total - 1));   /* real frames = total - 1 (_C) */
    return ESP_OK;
}

static const rwave_clip_t *rwave_clip_for(emote_face_state_t st)
{
    switch (st) {
    case EMOTE_FACE_IDLE:      return &s_rw.idle;
    case EMOTE_FACE_LISTENING: return &s_rw.listen;
    case EMOTE_FACE_THINKING:  return &s_rw.think;
    case EMOTE_FACE_SPEAKING:  return &s_rw.speak;
    default:                   return NULL;
    }
}

/* ---- amplitude source ----------------------------------------------------- */

static float rwave_target_amp(emote_face_state_t st)
{
    int milli;
    if (s_rw.synth_amp >= 0) {
        milli = s_rw.synth_amp;          /* CLI synthetic 0..1000 */
    } else if (s_rw.amp_cb) {
        milli = s_rw.amp_cb(st);         /* live mic/out RMS, 0..1000 */
    } else {
        milli = 0;                       /* no source → flat (full loop still moves) */
    }
    if (milli < 0)    milli = 0;
    if (milli > 1000) milli = 1000;
    return milli / 1000.0f;
}

/* ---- segment programming -------------------------------------------------- */

/* Point the object's src at `clip` (only when it changes) then program the loop.
 * Must be called under emote_lock. */
static void rwave_apply_segment(const rwave_clip_t *clip, uint32_t end, uint32_t fps)
{
    if (!clip || !clip->loaded || !s_rw.obj) {
        return;
    }
    if (s_rw.cur_clip != clip) {
        gfx_anim_set_src(s_rw.obj, clip->data, clip->size);
        s_rw.cur_clip = clip;
        s_rw.last_end = -1;              /* force a fresh set_segment */
    }
    if (end < 1)            end = 1;             /* end>=1 so the loop draws (plan §2) */
    if (end > clip->last)   end = clip->last;
    if ((int)end == s_rw.last_end) {
        return;                          /* no change → don't thrash the engine */
    }
    s_rw.last_end = (int)end;
    gfx_anim_set_segment(s_rw.obj, 0, end, fps, /*repeat=*/true);
    gfx_anim_start(s_rw.obj);
}

/* ---- driver task ---------------------------------------------------------- */

static void rwave_task(void *arg)
{
    (void)arg;
    while (s_rw.run) {
        emote_face_state_t st = s_rw.state;
        const rwave_clip_t *clip = rwave_clip_for(st);

        if (st == EMOTE_FACE_OFF || !s_rw.obj || !clip || !clip->loaded) {
            vTaskDelay(pdMS_TO_TICKS(RWAVE_DRIVER_MS));
            continue;
        }

        /* ease displayed amplitude toward target for fluid motion */
        float target = (st == EMOTE_FACE_LISTENING || st == EMOTE_FACE_SPEAKING)
                           ? rwave_target_amp(st) : 0.0f;
        s_rw.disp_amp += (target - s_rw.disp_amp) * RWAVE_LERP;

        uint32_t end, fps;
        if (st == EMOTE_FACE_LISTENING || st == EMOTE_FACE_SPEAKING) {
            /* amplitude → segment end: louder plays deeper into the ramp. amp 0
             * → end 1 (flat line still loops/draws); amp 1.0 → end clip->last
             * (the baked peak frame at index clip->last-1 is displayed). */
            float a = s_rw.disp_amp;
            if (a < 0.0f) a = 0.0f; else if (a > 1.0f) a = 1.0f;
            end = 1 + (uint32_t)(a * (float)(clip->last - 1) + 0.5f);
            fps = RWAVE_FPS_REACTIVE;
        } else if (st == EMOTE_FACE_THINKING) {
            end = clip->last;            /* full self-contained sweep loop */
            fps = RWAVE_FPS_THINK;
        } else { /* IDLE */
            end = clip->last;            /* full breathing loop */
            fps = RWAVE_FPS_IDLE;
        }

        if (display_arbiter_is_owner(DISPLAY_ARBITER_OWNER_EMOTE)) {
            emote_lock(s_rw.emote);
            rwave_apply_segment(clip, end, fps);
            emote_unlock(s_rw.emote);
        }

        vTaskDelay(pdMS_TO_TICKS(RWAVE_DRIVER_MS));
    }
    s_rw.task = NULL;
    vTaskDelete(NULL);
}

/* ---- public API (matches emote.h declarations) ---------------------------- */

esp_err_t emote_face_init(emote_handle_t emote)
{
    ESP_RETURN_ON_FALSE(emote, ESP_ERR_INVALID_ARG, TAG, "null emote handle");
    if (s_rw.obj) {
        return ESP_OK;   /* already initialised */
    }
    s_rw.emote = emote;
    s_rw.synth_amp = -1;
    s_rw.last_end = -1;
    s_rw.cur_clip = NULL;

    /* Load the four baked clips from the `emote` asset partition. A missing clip
     * is non-fatal: that state just won't show (best-effort, like emote.c's
     * face-init guard). At least one must load for the face to be useful. */
    int ok = 0;
    ok += (rwave_load_clip(RWAVE_ASSET_IDLE,   &s_rw.idle)   == ESP_OK);
    ok += (rwave_load_clip(RWAVE_ASSET_LISTEN, &s_rw.listen) == ESP_OK);
    ok += (rwave_load_clip(RWAVE_ASSET_THINK,  &s_rw.think)  == ESP_OK);
    ok += (rwave_load_clip(RWAVE_ASSET_SPEAK,  &s_rw.speak)  == ESP_OK);
    if (ok == 0) {
        ESP_LOGW(TAG, "no reactive face assets found in '%s' partition — face "
                      "disabled, baked emote eye stays up", "emote");
        return ESP_OK;   /* don't fail emote_start; the eye still works */
    }

    /* Create the custom anim object on the emote display, centred, hidden. */
    s_rw.obj = emote_create_obj_by_type(emote, EMOTE_OBJ_TYPE_ANIM, RWAVE_OBJ_NAME);
    ESP_RETURN_ON_FALSE(s_rw.obj, ESP_FAIL, TAG, "failed to create rwave anim obj");
    gfx_obj_align(s_rw.obj, GFX_ALIGN_CENTER, 0, 0);
    emote_set_obj_visible(emote, RWAVE_OBJ_NAME, false);

    s_rw.run = true;
    s_rw.state = EMOTE_FACE_OFF;
    BaseType_t started = xTaskCreate(rwave_task, "rwave", 4096, NULL, 3, &s_rw.task);
    ESP_RETURN_ON_FALSE(started == pdPASS, ESP_FAIL, TAG, "failed to start rwave task");

    ESP_LOGI(TAG, "reactive waveform face ready (baked EAF, %d clips loaded)", ok);
    return ESP_OK;
}

esp_err_t emote_face_set_state(emote_face_state_t state)
{
    s_rw.state = state;
    if (!s_rw.obj) {
        return ESP_OK;   /* applied once initialised */
    }

    bool show = (state != EMOTE_FACE_OFF);
    /* Show the waveform for any active state; hide it (restore the emote eye) on
     * OFF. Mirrors waveform.c's visibility contract. */
    emote_set_obj_visible(s_rw.emote, RWAVE_OBJ_NAME, show);
    emote_set_anim_visible(s_rw.emote, !show);   /* hide the eye while active */

    if (state == EMOTE_FACE_IDLE || state == EMOTE_FACE_THINKING) {
        s_rw.disp_amp = 0.0f;
    }
    /* The driver task picks up the new state on its next tick and programs the
     * matching clip + segment; nothing else to do here. */
    return ESP_OK;
}

void emote_face_set_synthetic_amplitude(int amp_milli)
{
    s_rw.synth_amp = amp_milli;   /* <0 restores the live cb */
}

void emote_face_set_amplitude_source(emote_face_amp_cb_t cb)
{
    s_rw.amp_cb = cb;
}
