#!/usr/bin/env python3
"""Live JarvisRobot device diagnostics over the local HTTP API."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any


DEFAULT_HOST = os.environ.get("JARVIS_DEVICE_HOST", "")
REPORT_DIR = ".build_logs/live-device"
ROUTE_UNAVAILABLE_CODES = {404, 405, 410, 501}
AUDIO_TAP_SOURCES = ("mic-clean", "mic-raw", "reference", "playback")
KEYCHAIN_SERVICE = "com.ingeniousdigital.jarvisnano.desk"
MAX_PAIRING_TOKEN_BYTES = 64

# Evidence generated by this CLI is deliberately conservative. A framebuffer
# mirror and a successful control request are useful, but neither can see the
# glass or hear the speaker. Do not let a green HTTP response impersonate a
# physical test. It has enough confidence already.
PROOF_SCOPE = {
    "display_snapshot": {
        "level": "software_mirror",
        "proves": "pixels submitted by firmware to the panel path",
        "does_not_prove": "that the physical AMOLED displayed those pixels",
    },
    "display_test_command": {
        "level": "control_path",
        "proves": "the firmware accepted a deterministic panel-pattern request",
        "does_not_prove": "that a person or camera observed the pattern on the panel",
    },
    "audio_mic_tap": {
        "level": "electrical_software_path",
        "proves": "PCM samples reached the selected firmware capture tap",
        "does_not_prove": "microphone acoustic sensitivity without signal analysis",
    },
    "audio_playback_tap": {
        "level": "software_path",
        "proves": "PCM samples reached the firmware playback tap",
        "does_not_prove": "audible output from the physical speaker",
    },
    "audio_reference_tap": {
        "level": "electrical_reference_path",
        "proves": "reference-lane PCM reached the firmware capture tap",
        "does_not_prove": "physical speaker output or acoustic microphone pickup",
    },
    "audio_self_test": {
        "level": "bounded_test_command",
        "proves": "the firmware accepted or ran its bounded audio diagnostic",
        "does_not_prove": "physical acoustic loopback unless returned metrics say so",
    },
    "physical": {
        "level": "external_observation_required",
        "proves": "nothing automatically",
        "does_not_prove": "panel visibility, touch registration, or audible speaker output",
    },
}

SIGNATURES = [
    ("FAIL", "Gateway stop timed out", "Gemini stop path blocked"),
    ("FAIL", "WS connect timeout", "Gemini WebSocket connection timeout"),
    ("FAIL", "setupComplete timeout", "Gemini setupComplete missing"),
    ("FAIL", "Current mode playback conflict", "Audio mode conflict"),
    ("OK", "Current mode(playback) and peer mode have same sample_rate", "Audio playback/record rates matched"),
    ("OK", "Tap: local scene", "Touch routed to local demo"),
    ("FAIL", "Touch controller must be initialized", "Touch controller init failed"),
    ("FAIL", "rwave_task skip: state=", "Reactive face task is skipping frames"),
    ("FAIL", "display arbiter NOT owned", "Reactive face does not own display"),
    ("FAIL", "display snapshot unavailable", "Display snapshot mirror unavailable"),
    ("FAIL", "WS start returned ESP_FAIL", "Gemini WebSocket task failed to start"),
    ("FAIL", "display flush sync disabled", "Display flush sync disabled after timeouts"),
    ("WARN", "display flush completion timeout", "Display flush completion timeout"),
    ("WARN", "i2s_channel_disable", "I2S disable warning"),
    ("WARN", "No response received from Gemini", "Gemini did not return text/audio"),
    ("WARN", "audio_parts=0", "Gemini session produced no audio parts"),
    ("OK", "WS start returned ESP_OK", "Gemini WebSocket task started"),
    ("OK", "setupComplete", "Gemini setup complete"),
    ("OK", "Tap: toggling Gemini Live on", "Touch routed to Gemini start"),
    ("OK", "Tap: toggling Gemini Live off", "Touch routed to Gemini stop"),
    ("OK", "rwave state applied", "Reactive face state applied"),
    ("OK", "display snapshot stream", "Display snapshot requested"),
    ("OK", "display snapshot saved", "Display snapshot saved to SD"),
]

BOOT_MARKERS = (
    "jarvis_logger: persistent logging ->",
    "app: Persistent logging",
)


@dataclass
class Check:
    level: str
    label: str
    detail: str


def pairing_keychain_account(base_url: str) -> str:
    return "jarvis-desk@" + urllib.parse.urlsplit(base_url).netloc


def valid_pairing_token(value: str) -> bool:
    encoded = value.encode("utf-8")
    return (
        bool(value)
        and len(encoded) <= MAX_PAIRING_TOKEN_BYTES
        and all(not ch.isspace() and 0x21 <= ord(ch) < 0x7F for ch in value)
    )


def load_pairing_token(base_url: str) -> str | None:
    """Load the host-bound control token without putting it in argv/output."""
    account = pairing_keychain_account(base_url)
    try:
        result = subprocess.run(
            [
                "security",
                "find-generic-password",
                "-a",
                account,
                "-s",
                KEYCHAIN_SERVICE,
                "-w",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=5,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        result = None
    if result is not None and result.returncode == 0:
        token = result.stdout.rstrip("\r\n")
        return token if valid_pairing_token(token) else None

    # Environment fallback is allowed only when explicitly bound to the same
    # device host. This avoids accidentally sending one Nano's token to another.
    token = os.environ.get("JARVIS_DESK_TOKEN", "")
    configured_host = os.environ.get("JARVIS_DEVICE_HOST", "").strip()
    if not token or not configured_host:
        return None
    if not configured_host.startswith(("http://", "https://")):
        configured_host = "http://" + configured_host
    if configured_host.rstrip("/") != base_url or not valid_pairing_token(token):
        return None
    return token


class Device:
    def __init__(self, host: str, timeout: float) -> None:
        base = host.strip()
        if not base.startswith(("http://", "https://")):
            base = "http://" + base
        self.base = base.rstrip("/")
        self.timeout = timeout
        self._pairing_token = load_pairing_token(self.base)

    def request(self, method: str, path: str, body: dict[str, Any] | None = None) -> tuple[int, str, Any]:
        data = None
        headers = {"Accept": "application/json,text/plain,*/*"}
        if self._pairing_token:
            headers["X-JarvisNano-Token"] = self._pairing_token
        if method.upper() != "GET":
            headers["X-JarvisNano-Control"] = "1"
        if body is not None:
            data = json.dumps(body).encode("utf-8")
            headers["Content-Type"] = "application/json"
        req = urllib.request.Request(self.base + path, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
                parsed: Any = None
                try:
                    parsed = json.loads(raw)
                except json.JSONDecodeError:
                    parsed = raw
                return resp.status, raw, parsed
        except urllib.error.HTTPError as exc:
            raw = exc.read().decode("utf-8", errors="replace")
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError:
                parsed = raw
            return exc.code, raw, parsed

    def get(self, path: str) -> tuple[int, str, Any]:
        return self.request("GET", path)

    def post(self, path: str, body: dict[str, Any]) -> tuple[int, str, Any]:
        return self.request("POST", path, body)

    def get_bytes(self, path: str) -> tuple[int, dict[str, str], bytes]:
        req = urllib.request.Request(self.base + path, headers={"Accept": "*/*"}, method="GET")
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                return resp.status, dict(resp.headers.items()), resp.read()
        except urllib.error.HTTPError as exc:
            return exc.code, dict(exc.headers.items()), exc.read()


def now_slug() -> str:
    return dt.datetime.now().strftime("%Y%m%d-%H%M%S")


def status_value(payload: Any, *names: str) -> Any:
    if not isinstance(payload, dict):
        return None
    for name in names:
        if name in payload:
            return payload[name]
    return None


def short_json(value: Any) -> str:
    if isinstance(value, (dict, list)):
        return json.dumps(value, sort_keys=True, separators=(",", ":"))[:500]
    return str(value).strip()[:500]


def route_unavailable(code: int) -> bool:
    return code in ROUTE_UNAVAILABLE_CODES


def print_route_result(path: str, code: int, body: Any) -> bool:
    """Print a route result and return True only when it succeeded."""
    if route_unavailable(code):
        print_check("N/A", f"{path} http={code}", "route is not present in this firmware")
        return False
    ok = 200 <= code < 300
    print_check("OK" if ok else "FAIL", f"{path} http={code}", short_json(body))
    return ok


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def header_value(headers: dict[str, str], name: str, default: str = "") -> str:
    wanted = name.lower()
    for key, value in headers.items():
        if key.lower() == wanted:
            return value
    return default


def write_bytes(path: str, data: bytes) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(data)


def write_json(path: str, value: Any) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(value, fh, indent=2, sort_keys=True)
        fh.write("\n")


def ppm_dimensions(data: bytes) -> tuple[int, int] | None:
    """Return P6 dimensions without accepting an arbitrary HTTP 200 as an image."""
    try:
        header = data[:128].split()
        if len(header) < 4 or header[0] != b"P6" or header[3] != b"255":
            return None
        width, height = int(header[1]), int(header[2])
        if width <= 0 or height <= 0:
            return None
        # The v5 route emits a compact header with no comments. Validate the
        # payload length as well, so a dropped chunk cannot masquerade as a
        # successful screen capture.
        marker = f"{header[2].decode()}\n255\n".encode()
        marker_at = data.find(marker)
        if marker_at < 0:
            marker = f"{header[2].decode()}\r\n255\r\n".encode()
            marker_at = data.find(marker)
        if marker_at < 0:
            return None
        pixel_offset = marker_at + len(marker)
        if len(data) - pixel_offset != width * height * 3:
            return None
        return width, height
    except (ValueError, IndexError):
        return None


def rgb565_be_to_ppm(data: bytes, width: int, height: int) -> bytes | None:
    """Convert native big-endian RGB565 bytes to P6 on the host."""
    if width <= 0 or height <= 0 or len(data) != width * height * 2:
        return None
    rgb = bytearray(width * height * 3)
    for pixel in range(width * height):
        offset = pixel * 2
        value = (data[offset] << 8) | data[offset + 1]
        r = (value >> 11) & 0x1F
        g = (value >> 5) & 0x3F
        b = value & 0x1F
        dst = pixel * 3
        rgb[dst] = (r << 3) | (r >> 2)
        rgb[dst + 1] = (g << 2) | (g >> 4)
        rgb[dst + 2] = (b << 3) | (b >> 2)
    return f"P6\n{width} {height}\n255\n".encode("ascii") + rgb


def fetch_display_ppm(dev: Device, query: str = "") -> tuple[int, dict[str, str], bytes]:
    """Prefer the smaller exact RGB565 route; fall back to legacy PPM."""
    code, headers, raw = dev.get_bytes(f"/api/display/snapshot.rgb565{query}")
    if code == 200:
        try:
            width = int(header_value(headers, "X-Jarvis-Display-Width"))
            height = int(header_value(headers, "X-Jarvis-Display-Height"))
        except ValueError:
            width = height = 0
        ppm = rgb565_be_to_ppm(raw, width, height)
        if ppm is not None:
            converted_headers = dict(headers)
            converted_headers["X-Jarvis-Mirror-Transport"] = "rgb565"
            return code, converted_headers, ppm
    return dev.get_bytes(f"/api/display/snapshot.ppm{query}")


def wav_info(data: bytes) -> dict[str, Any] | None:
    """Validate the fixed PCM WAV fields used by the diagnostic tap routes."""
    if len(data) < 44 or data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        return None
    # The firmware emits canonical RIFF/PCM with fmt first. Avoid importing the
    # wave module here because it rejects some still-valid streaming sizes.
    if data[12:16] != b"fmt " or data[36:40] != b"data":
        return None
    byte_order = "little"
    audio_format = int.from_bytes(data[20:22], byte_order)
    channels = int.from_bytes(data[22:24], byte_order)
    sample_rate = int.from_bytes(data[24:28], byte_order)
    bits_per_sample = int.from_bytes(data[34:36], byte_order)
    declared_data_bytes = int.from_bytes(data[40:44], byte_order)
    if (
        audio_format != 1
        or channels != 1
        or sample_rate <= 0
        or bits_per_sample != 16
        or declared_data_bytes > len(data) - 44
    ):
        return None
    data_bytes = declared_data_bytes
    bytes_per_sample = max(1, channels * bits_per_sample // 8)
    samples = data_bytes // bytes_per_sample
    return {
        "audio_format": audio_format,
        "channels": channels,
        "sample_rate_hz": sample_rate,
        "bits_per_sample": bits_per_sample,
        "data_bytes": data_bytes,
        "samples_per_channel": samples,
        "duration_ms": round(samples * 1000 / sample_rate, 1) if sample_rate else 0,
    }


def capture_display_info(dev: Device) -> dict[str, Any]:
    path = "/api/display/snapshot.json"
    try:
        code, raw, body = dev.get(path)
        result = {"http": code, "body": body, "raw": raw[:4000]}
        print_route_result(path, code, body)
        if code == 200 and isinstance(body, dict):
            readback = bool(body.get("panel_readback", False))
            level = "physical_panel_readback" if readback else "software_mirror"
            print_check(
                "PROOF",
                "display evidence scope",
                f"{level}; physical panel visibility remains externally observed",
            )
        return result
    except Exception as exc:  # noqa: BLE001 - bundle records partial diagnostics.
        print_check("N/A", path, str(exc))
        return {"error": str(exc)}


def capture_display_ppm(dev: Device, output_dir: str, stem: str = "display") -> dict[str, Any]:
    path = "/api/display/snapshot.ppm"
    try:
        code, headers, data = fetch_display_ppm(dev)
    except Exception as exc:  # noqa: BLE001
        print_check("N/A", path, str(exc))
        return {"error": str(exc), "proof": PROOF_SCOPE["display_snapshot"]}

    result: dict[str, Any] = {
        "http": code,
        "headers": headers,
        "bytes": len(data),
        "sha256": sha256_hex(data),
        "proof": PROOF_SCOPE["display_snapshot"],
    }
    if code != 200:
        result["body"] = data.decode("utf-8", errors="replace")[:1000]
        print_route_result(path, code, result["body"])
        return result

    dims = ppm_dimensions(data)
    if dims is None:
        result["error"] = "HTTP 200 body is not a supported P6 PPM"
        print_check("FAIL", path, result["error"])
        return result

    os.makedirs(output_dir, exist_ok=True)
    ppm_path = os.path.join(output_dir, f"{stem}.ppm")
    write_bytes(ppm_path, data)
    result.update({"path": ppm_path, "width": dims[0], "height": dims[1]})
    png_path = convert_ppm_to_png(ppm_path)
    if png_path:
        result["png_path"] = png_path
    panel_readback = header_value(headers, "X-Jarvis-Panel-Readback", "false").lower() == "true"
    result["panel_readback"] = panel_readback
    print_check("OK", "display snapshot saved", f"{ppm_path} {dims[0]}x{dims[1]}")
    print_check(
        "PROOF",
        "display snapshot",
        "physical panel readback" if panel_readback else "software mirror only; inspect the real panel separately",
    )
    return result


def classify_logs(log_text: str) -> list[Check]:
    checks: list[Check] = []
    for level, needle, label in SIGNATURES:
        if needle in log_text:
            checks.append(Check(level, label, needle))
    return checks


def log_window_for_checks(log_text: str, max_lines: int | None = None) -> str:
    """Classify the current boot/window, not stale SD log lines from an older run."""
    lines = log_text.splitlines()
    start = 0
    for idx, line in enumerate(lines):
        if any(marker in line for marker in BOOT_MARKERS):
            start = idx
    window = lines[start:]
    if max_lines is not None:
        window = window[-max_lines:]
    return "\n".join(window)


def print_check(level: str, label: str, detail: str = "") -> None:
    suffix = f" - {detail}" if detail else ""
    print(f"{level:<4} {label}{suffix}")


def collect_snapshot(dev: Device, tail: int) -> dict[str, Any]:
    snapshot: dict[str, Any] = {
        "base": dev.base,
        "captured_at": dt.datetime.now().isoformat(timespec="seconds"),
        "endpoints": {},
    }
    for path in (
        "/api/cockpit",
        "/api/gemini/live",
        "/api/touch",
        "/api/audio/taps",
        "/api/agent/link",
        "/api/display",
        "/api/display/snapshot.json",
    ):
        try:
            code, raw, parsed = dev.get(path)
            snapshot["endpoints"][path] = {"http": code, "body": parsed, "raw": raw[:2000]}
        except Exception as exc:  # noqa: BLE001 - CLI diagnostic should report transport detail.
            snapshot["endpoints"][path] = {"error": str(exc)}
    try:
        code, raw, _ = dev.get(f"/api/logs?tail={tail}")
        snapshot["logs"] = {"http": code, "tail": tail, "text": raw}
    except Exception as exc:  # noqa: BLE001
        snapshot["logs"] = {"error": str(exc), "text": ""}
    return snapshot


def print_snapshot(snapshot: dict[str, Any]) -> int:
    failures = 0
    for path, result in snapshot["endpoints"].items():
        if "error" in result:
            print_check("FAIL", path, result["error"])
            failures += 1
            continue
        code = result["http"]
        body = result.get("body")
        level = "N/A" if route_unavailable(code) else (
            "OK" if 200 <= code < 300 else "FAIL"
        )
        if level == "FAIL":
            failures += 1
        detail = "route is not present in this firmware" \
            if level == "N/A" else short_json(body)
        print_check(level, f"{path} http={code}", detail)

    logs = snapshot.get("logs", {})
    if "error" in logs:
        print_check("FAIL", "/api/logs", logs["error"])
        failures += 1
    else:
        log_code = int(logs.get("http") or 0)
        if route_unavailable(log_code):
            print_check("N/A", f"/api/logs http={log_code}",
                        "route is not present in this firmware")
        elif 200 <= log_code < 300:
            print_check("OK", f"/api/logs http={log_code} tail={logs.get('tail')}")
            for check in classify_logs(log_window_for_checks(str(logs.get("text", "")))):
                print_check(check.level, check.label, check.detail)
                if check.level == "FAIL":
                    failures += 1
        else:
            print_check("FAIL", f"/api/logs http={log_code}",
                        str(logs.get("text", ""))[:500])
            failures += 1
    return failures


def command_status(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    snapshot = collect_snapshot(dev, args.tail)
    failures = print_snapshot(snapshot)
    if args.json:
        print(json.dumps(snapshot, indent=2, sort_keys=True))
    return 1 if failures else 0


def wait_gemini_state(dev: Device, wanted: set[str], deadline: float) -> tuple[bool, Any]:
    last: Any = None
    while time.time() < deadline:
        code, _, body = dev.get("/api/gemini/live")
        last = body
        if code == 200:
            state = str(status_value(body, "phase", "state", "status") or "").upper()
            if state in wanted:
                return True, body
        time.sleep(0.5)
    return False, last


def command_gemini_cycle(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    failures = 0

    initial_code, _, initial = dev.get("/api/gemini/live")
    initially_paused = bool(initial.get("privacy_paused")) \
        if initial_code == 200 and isinstance(initial, dict) else True

    print_check("RUN", "Gemini start")
    code, _, body = dev.post("/api/voice/control?armed=1", {})
    print_check("OK" if 200 <= code < 300 else "FAIL",
                f"POST /api/voice/control?armed=1 http={code}", short_json(body))
    if not (200 <= code < 300):
        return 1

    ok, body = wait_gemini_state(dev, {"LISTENING", "SPEAKING", "THINKING"}, time.time() + args.start_timeout)
    print_check("OK" if ok else "FAIL", "Gemini active state", short_json(body))
    failures += 0 if ok else 1

    if args.text:
        print_check("RUN", "Gemini text turn", args.text)
        query = urllib.parse.urlencode({"text": args.text})
        code, _, body = dev.post(f"/api/debug/say?{query}", {})
        print_check("OK" if 200 <= code < 300 else "FAIL",
                    f"POST /api/debug/say http={code}", short_json(body))
        failures += 0 if 200 <= code < 300 else 1
        time.sleep(args.turn_wait)

    code, _, body = dev.get("/api/gemini/live")
    print_check("OK" if code == 200 else "FAIL", f"Gemini status http={code}", short_json(body))
    if isinstance(body, dict):
        parts = int(body.get("audio_chunks") or 0)
        if args.text and parts <= 0:
            print_check("WARN", "No audio parts observed after text turn", f"audio_parts={parts}")

    print_check("RUN", "Gemini stop")
    code, _, body = dev.post("/api/voice/control?armed=0", {})
    print_check("OK" if 200 <= code < 300 else "FAIL",
                f"POST /api/voice/control?armed=0 http={code}", short_json(body))
    failures += 0 if 200 <= code < 300 else 1

    ok, body = wait_gemini_state(dev, {"IDLE", "STOPPED"}, time.time() + args.stop_timeout)
    print_check("OK" if ok else "FAIL", "Gemini idle after stop", short_json(body))
    failures += 0 if ok else 1

    if not initially_paused:
        print_check("RUN", "restore always-ready voice")
        code, _, body = dev.post("/api/voice/control?armed=1", {})
        restored, body = wait_gemini_state(
            dev, {"LISTENING", "SPEAKING", "THINKING"},
            time.time() + args.start_timeout,
        ) if 200 <= code < 300 else (False, body)
        print_check("OK" if restored else "FAIL", "always-ready voice restored",
                    short_json(body))
        failures += 0 if restored else 1

    snapshot = collect_snapshot(dev, args.tail)
    logs = str(snapshot.get("logs", {}).get("text", ""))
    for check in classify_logs(log_window_for_checks(logs)):
        print_check(check.level, check.label, check.detail)
        if check.level == "FAIL":
            failures += 1

    if args.report:
        write_report(snapshot, "gemini-cycle")
    return 1 if failures else 0


def command_logs(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    code, raw, _ = dev.get(f"/api/logs?tail={args.tail}")
    if code != 200:
        print_check("FAIL", f"/api/logs http={code}", raw[:500])
        return 1
    needles = [x.strip() for x in args.grep.split(",") if x.strip()]
    lines = raw.splitlines()
    if needles:
        lines = [line for line in lines if any(needle.lower() in line.lower() for needle in needles)]
    visible_lines = lines[-args.lines :]
    for line in visible_lines:
        print(line)
    failures = 0
    for check in classify_logs(log_window_for_checks(raw)):
        print_check(check.level, check.label, check.detail)
        failures += 1 if check.level == "FAIL" else 0
    return 1 if failures else 0


def write_report(snapshot: dict[str, Any], prefix: str) -> str:
    os.makedirs(REPORT_DIR, exist_ok=True)
    path = os.path.join(REPORT_DIR, f"{now_slug()}-{prefix}.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(snapshot, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print_check("OK", "report written", path)
    return path


def convert_ppm_to_png(ppm_path: str) -> str | None:
    png_path = ppm_path[:-4] + ".png" if ppm_path.endswith(".ppm") else ppm_path + ".png"
    if shutil.which("sips"):
        result = subprocess.run(
            ["sips", "-s", "format", "png", ppm_path, "--out", png_path],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode == 0 and os.path.exists(png_path):
            return png_path
    if shutil.which("magick"):
        result = subprocess.run(
            ["magick", ppm_path, png_path],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode == 0 and os.path.exists(png_path):
            return png_path
    return None


def command_screen(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    info_result = capture_display_info(dev)
    query = "?save=1" if args.save_sd else ""
    code, headers, data = fetch_display_ppm(dev, query)
    if code != 200:
        detail = data.decode("utf-8", errors="replace")[:500]
        print_check("FAIL", f"/api/display/snapshot.ppm http={code}", detail)
        return 1
    dims = ppm_dimensions(data)
    if dims is None:
        print_check("FAIL", "/api/display/snapshot.ppm", "HTTP 200 body is not a supported P6 PPM")
        return 1

    os.makedirs(REPORT_DIR, exist_ok=True)
    ppm_path = os.path.join(REPORT_DIR, f"{now_slug()}-screen.ppm")
    with open(ppm_path, "wb") as fh:
        fh.write(data)

    capture_source = header_value(headers, "X-Jarvis-Display-Source", "unknown")
    display_owner = header_value(headers, "X-Jarvis-Display-Owner", "unknown")
    panel_readback = header_value(headers, "X-Jarvis-Panel-Readback", "false")
    mirror_fresh = header_value(headers, "X-Jarvis-Display-Fresh", "unknown")
    print_check("OK", "display software mirror captured", ppm_path)
    print_check("OK", "display image", f"{dims[0]}x{dims[1]} sha256={sha256_hex(data)[:16]}")
    print_check(
        "OK",
        "display capture source",
        f"source={capture_source} owner={display_owner} panel_readback={panel_readback} mirror_fresh={mirror_fresh}",
    )
    if str(panel_readback).lower() != "true":
        print_check(
            "PROOF",
            "display evidence scope",
            "software mirror/control-path evidence; physical panel remains camera/person verified",
        )
    saved_path = header_value(headers, "X-Jarvis-Saved-Path")
    if saved_path:
        print_check("OK", "device SD copy", saved_path)
    frame = header_value(headers, "X-Jarvis-Display-Frame")
    if frame:
        header_dims = (
            f"{header_value(headers, 'X-Jarvis-Display-Width', '?')}x"
            f"{header_value(headers, 'X-Jarvis-Display-Height', '?')}"
        )
        print_check("OK", "display frame", f"{frame} {header_dims}")

    png_path = convert_ppm_to_png(ppm_path) if args.png else None
    if png_path:
        print_check("OK", "PNG converted", png_path)
    elif args.png:
        print_check("WARN", "PNG conversion skipped", "sips/magick unavailable or failed")

    if args.logs:
        try:
            _, raw, _ = dev.get(f"/api/logs?tail={args.tail}")
            for check in classify_logs(log_window_for_checks(raw)):
                print_check(check.level, check.label, check.detail)
        except Exception as exc:  # noqa: BLE001
            print_check("WARN", "log integration unavailable", str(exc))
    return 0 if "error" not in info_result else 1


def command_display_test(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    path = "/api/display/test?" + urllib.parse.urlencode({"pattern": args.pattern})
    try:
        code, _, body = dev.request("POST", path)
    except Exception as exc:  # noqa: BLE001
        print_check("N/A", "/api/display/test", str(exc))
        return 1

    ok = print_route_result("/api/display/test", code, body)
    if not ok:
        return 0 if route_unavailable(code) else 1
    print_check(
        "PROOF",
        "display test command",
        "control path accepted; observe the physical panel to prove glass output",
    )

    failures = 0
    if args.wait > 0:
        time.sleep(args.wait)
    if args.screen:
        screen_args = argparse.Namespace(
            host=args.host,
            timeout=args.timeout,
            tail=args.tail,
            save_sd=False,
            png=True,
            logs=False,
        )
        failures += command_screen(screen_args)
    if args.restore and args.pattern != "off":
        restore_path = "/api/display/test?pattern=off"
        code, _, restore_body = dev.request("POST", restore_path)
        if print_route_result(restore_path, code, restore_body):
            print_check("OK", "display renderer restored", "pattern=off")
        else:
            failures += 0 if route_unavailable(code) else 1
    return 1 if failures else 0


def start_audio_self_test(dev: Device) -> dict[str, Any]:
    path = "/api/audio/self-test"
    attempts: list[dict[str, Any]] = []
    # Current firmware uses explicit POST intent; GET remains a compatibility
    # fallback for older bench images.
    for method in ("POST", "GET"):
        try:
            code, raw, body = dev.request(method, path)
        except Exception as exc:  # noqa: BLE001
            attempts.append({"method": method, "error": str(exc)})
            continue
        attempts.append({"method": method, "http": code, "body": body, "raw": raw[:4000]})
        if 200 <= code < 300:
            print_check("OK", f"{method} {path} http={code}", short_json(body))
            print_check(
                "PROOF",
                "audio self-test",
                "bounded diagnostic accepted; inspect tap metrics/WAVs for path evidence",
            )
            return {"ok": True, "method": method, "http": code, "body": body, "attempts": attempts,
                    "proof": PROOF_SCOPE["audio_self_test"]}
        if not route_unavailable(code):
            print_check("FAIL", f"{method} {path} http={code}", short_json(body))
            return {"ok": False, "method": method, "http": code, "body": body, "attempts": attempts,
                    "proof": PROOF_SCOPE["audio_self_test"]}
    detail = "route is not present in this firmware"
    if attempts and all("error" in attempt for attempt in attempts):
        detail = "; ".join(str(attempt["error"]) for attempt in attempts)
    print_check("N/A", path, detail)
    return {"ok": False, "unavailable": True, "attempts": attempts,
            "proof": PROOF_SCOPE["audio_self_test"]}


def wait_audio_self_test_complete(dev: Device, timeout: float) -> bool:
    """Wait for the queued test to actually start and finish.

    Always-ready voice may need a graceful drain before the diagnostic owns the
    codec, so sleeping from HTTP acceptance can download a truncated capture.
    """
    deadline = time.monotonic() + max(timeout, 4.0)
    observed = False
    while time.monotonic() < deadline:
        try:
            code, _, body = dev.get("/api/gemini/live")
        except Exception:  # noqa: BLE001 - caller still has a bounded fallback.
            time.sleep(0.15)
            continue
        if code == 200 and isinstance(body, dict):
            queued = bool(body.get("audio_diag_queued"))
            running = bool(body.get("audio_diag_running"))
            observed = observed or queued or running
            if observed and not queued and not running:
                print_check("OK", "audio capture window", "diagnostic completed")
                return True
        time.sleep(0.15)
    print_check("WARN", "audio capture window", "completion was not observed before timeout")
    return False


def capture_audio_metrics(dev: Device, output_dir: str | None = None) -> dict[str, Any]:
    path = "/api/audio/taps"
    try:
        code, raw, body = dev.get(path)
    except Exception as exc:  # noqa: BLE001
        print_check("N/A", path, str(exc))
        return {"error": str(exc)}
    result: dict[str, Any] = {"http": code, "body": body, "raw": raw[:12000]}
    print_route_result(path, code, body)
    if output_dir is not None:
        os.makedirs(output_dir, exist_ok=True)
        if isinstance(body, (dict, list)):
            write_json(os.path.join(output_dir, "audio-taps.json"), body)
        else:
            write_bytes(os.path.join(output_dir, "audio-taps.txt"), raw.encode("utf-8"))
    return result


def download_audio_taps(dev: Device, output_dir: str,
                        sources: tuple[str, ...] | list[str]) -> dict[str, Any]:
    os.makedirs(output_dir, exist_ok=True)
    results: dict[str, Any] = {}
    for source in sources:
        path = "/api/audio/tap.wav?" + urllib.parse.urlencode({"source": source})
        try:
            code, headers, data = dev.get_bytes(path)
        except Exception as exc:  # noqa: BLE001
            print_check("N/A", f"audio tap {source}", str(exc))
            results[source] = {"error": str(exc)}
            continue

        if source == "playback":
            proof = PROOF_SCOPE["audio_playback_tap"]
        elif source == "reference":
            proof = PROOF_SCOPE["audio_reference_tap"]
        else:
            proof = PROOF_SCOPE["audio_mic_tap"]
        result: dict[str, Any] = {
            "http": code,
            "headers": headers,
            "bytes": len(data),
            "sha256": sha256_hex(data),
            "proof": proof,
        }
        results[source] = result
        if code != 200:
            result["body"] = data.decode("utf-8", errors="replace")[:1000]
            print_route_result(f"audio tap {source}", code, result["body"])
            continue

        info = wav_info(data)
        if info is None:
            result["error"] = "HTTP 200 body is not canonical PCM WAV"
            print_check("FAIL", f"audio tap {source}", result["error"])
            continue
        wav_path = os.path.join(output_dir, f"audio-{source}.wav")
        write_bytes(wav_path, data)
        result.update({"path": wav_path, "wav": info})
        firmware_level = header_value(headers, "X-Jarvis-Evidence-Level", "unknown")
        result["firmware_evidence_level"] = firmware_level
        print_check(
            "OK",
            f"audio tap {source}",
            f"{wav_path} {info['sample_rate_hz']}Hz {info['duration_ms']}ms firmware_level={firmware_level}",
        )
        print_check("PROOF", f"audio tap {source}", proof["level"] + "; " + proof["does_not_prove"])
    return results


def command_audio_taps(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    output_dir = args.output or os.path.join(REPORT_DIR, f"{now_slug()}-audio-taps")
    metrics = capture_audio_metrics(dev, output_dir)
    taps = download_audio_taps(dev, output_dir, args.source)
    write_json(
        os.path.join(output_dir, "manifest.json"),
        {
            "captured_at": dt.datetime.now().astimezone().isoformat(timespec="seconds"),
            "device": dev.base,
            "metrics": metrics,
            "taps": taps,
            "physical_proof": "not established by this CLI",
        },
    )
    successes = sum(1 for result in taps.values() if result.get("http") == 200 and "wav" in result)
    metrics_ok = metrics.get("http") == 200
    if successes or metrics_ok:
        print_check("OK", "audio evidence directory", output_dir)
        return 0
    if metrics.get("http") in ROUTE_UNAVAILABLE_CODES or any(
        result.get("http") in ROUTE_UNAVAILABLE_CODES for result in taps.values()
    ):
        print_check("N/A", "audio tap diagnostics", "routes are not present in this firmware")
        return 0
    return 1


def command_audio_self_test(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    output_dir = args.output or os.path.join(REPORT_DIR, f"{now_slug()}-audio-self-test")
    os.makedirs(output_dir, exist_ok=True)
    test = start_audio_self_test(dev)
    if test.get("ok") and args.wait > 0:
        print_check("WAIT", "audio capture window", "queued diagnostic + graceful voice drain")
        wait_audio_self_test_complete(dev, args.wait + 6.0)
    metrics = capture_audio_metrics(dev, output_dir)
    taps: dict[str, Any] = {}
    if args.download:
        taps = download_audio_taps(dev, output_dir, args.source)
    manifest = {
        "captured_at": dt.datetime.now().astimezone().isoformat(timespec="seconds"),
        "device": dev.base,
        "self_test": test,
        "metrics": metrics,
        "taps": taps,
        "physical_proof": "not established by this CLI",
    }
    write_json(os.path.join(output_dir, "manifest.json"), manifest)
    print_check("OK", "audio self-test evidence", output_dir)
    if test.get("unavailable"):
        return 0
    return 0 if test.get("ok") else 1


def command_report(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    snapshot = collect_snapshot(dev, args.tail)
    failures = print_snapshot(snapshot)
    write_report(snapshot, "report")
    return 1 if failures else 0


def command_evidence(args: argparse.Namespace) -> int:
    """Capture a timestamped, machine-readable device evidence bundle."""
    dev = Device(args.host, args.timeout)
    output_dir = args.output or os.path.join(REPORT_DIR, f"{now_slug()}-evidence")
    os.makedirs(output_dir, exist_ok=True)
    manifest: dict[str, Any] = {
        "schema": "jarvis-live-evidence/v1",
        "captured_at": dt.datetime.now().astimezone().isoformat(timespec="seconds"),
        "device": dev.base,
        "proof_scope": PROOF_SCOPE,
        "physical_proof": {
            "status": "not_established_by_cli",
            "required": [
                "person or camera observes the requested pattern on the AMOLED",
                "person completes touch targets on the physical glass",
                "person or calibrated microphone confirms speaker output",
            ],
        },
        "artifacts": {},
    }
    successes = 0

    # Broad status stays useful across old and new firmware. Individual 404s
    # are evidence of route availability, not a reason to abandon the bundle.
    status = collect_snapshot(dev, args.tail)
    write_json(os.path.join(output_dir, "runtime-status.json"), status)
    manifest["artifacts"]["runtime_status"] = "runtime-status.json"
    successes += sum(
        1 for result in status.get("endpoints", {}).values()
        if result.get("http") == 200
    )

    display_info = capture_display_info(dev)
    write_json(os.path.join(output_dir, "display-snapshot-info.json"), display_info)
    manifest["display"] = {"info": display_info}
    successes += 1 if display_info.get("http") == 200 else 0

    if args.pattern:
        pattern_path = "/api/display/test?" + urllib.parse.urlencode({"pattern": args.pattern})
        try:
            code, raw, body = dev.request("POST", pattern_path)
            pattern_result = {
                "http": code,
                "body": body,
                "raw": raw[:4000],
                "proof": PROOF_SCOPE["display_test_command"],
            }
            print_route_result("/api/display/test", code, body)
            successes += 1 if 200 <= code < 300 else 0
            manifest["display"]["test_pattern"] = pattern_result
            if 200 <= code < 300 and args.pattern_wait > 0:
                print_check("WAIT", "panel pattern observation window", f"{args.pattern_wait:.1f}s")
                time.sleep(args.pattern_wait)
        except Exception as exc:  # noqa: BLE001
            manifest["display"]["test_pattern"] = {"error": str(exc)}
            print_check("N/A", "/api/display/test", str(exc))

    display_capture = capture_display_ppm(dev, output_dir, "display-snapshot")
    manifest["display"]["snapshot"] = display_capture
    successes += 1 if display_capture.get("http") == 200 and "path" in display_capture else 0

    if args.pattern and not args.leave_pattern and args.pattern != "off":
        try:
            code, _, body = dev.request("POST", "/api/display/test?pattern=off")
            manifest["display"]["restore"] = {"http": code, "body": body}
            print_route_result("/api/display/test?pattern=off", code, body)
        except Exception as exc:  # noqa: BLE001
            manifest["display"]["restore"] = {"error": str(exc)}
            print_check("WARN", "display pattern restore", str(exc))

    if args.audio_self_test:
        manifest["audio_self_test"] = start_audio_self_test(dev)
        successes += 1 if manifest["audio_self_test"].get("ok") else 0
        if manifest["audio_self_test"].get("ok") and args.audio_wait > 0:
            print_check("WAIT", "audio diagnostic capture", "queued diagnostic + graceful voice drain")
            wait_audio_self_test_complete(dev, args.audio_wait + 6.0)

    audio_metrics = capture_audio_metrics(dev, output_dir)
    audio_taps = download_audio_taps(dev, output_dir, args.source)
    manifest["audio"] = {"metrics": audio_metrics, "taps": audio_taps}
    successes += 1 if audio_metrics.get("http") == 200 else 0
    successes += sum(
        1 for result in audio_taps.values()
        if result.get("http") == 200 and "wav" in result
    )

    physical_template = {
        "recorded_at": None,
        "observer": None,
        "display_pattern_observed": None,
        "display_matches_software_mirror": None,
        "touch_target_rounds_passed": None,
        "speaker_chirp_audible": None,
        "notes": "Fill this from a person/camera observation; the CLI intentionally cannot.",
    }
    write_json(os.path.join(output_dir, "physical-observation-template.json"), physical_template)
    manifest["artifacts"]["physical_observation_template"] = "physical-observation-template.json"

    # Write last so the manifest describes even partial captures and failures.
    write_json(os.path.join(output_dir, "manifest.json"), manifest)
    print_check("OK", "evidence bundle written", output_dir)
    print_check(
        "PROOF",
        "bundle boundary",
        "software/control/electrical evidence captured; physical observations remain explicit blanks",
    )
    if successes == 0:
        print_check("WARN", "no diagnostic route succeeded", "bundle records route/transport failures")
        return 1
    return 0


def command_restart(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    before_uptime = None
    try:
        _, _, health = dev.get("/api/health")
        if isinstance(health, dict):
            before_uptime = health.get("uptime_ms")
    except Exception:
        pass

    code, _, body = dev.post("/api/restart", {})
    print_check("OK" if 200 <= code < 300 else "FAIL", f"POST /api/restart http={code}", short_json(body))
    if not (200 <= code < 300):
        return 1

    saw_down = False
    deadline = time.time() + args.wait
    while time.time() < deadline:
        time.sleep(args.interval)
        try:
            code, _, body = dev.get("/api/health")
            if code == 200 and isinstance(body, dict):
                uptime = body.get("uptime_ms")
                if saw_down or before_uptime is None or (isinstance(uptime, (int, float)) and uptime < before_uptime):
                    print_check("OK", "device back online", short_json(body))
                    return 0
                print_check("WAIT", "device still online", f"uptime_ms={uptime}")
            else:
                saw_down = True
                print_check("WAIT", f"health http={code}", short_json(body))
        except Exception as exc:  # noqa: BLE001
            saw_down = True
            print_check("WAIT", "device down", str(exc)[:160])
    print_check("FAIL", "device did not return after restart", f"timeout={args.wait}s")
    return 1


def command_face(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    body = {"state": args.state}
    if args.amp is not None:
        body["amp"] = args.amp
    code, _, payload = dev.post("/api/display/face", body)
    print_check("OK" if 200 <= code < 300 else "FAIL", f"POST /api/display/face http={code}", short_json(payload))
    if not (200 <= code < 300):
        return 1
    if args.screen:
        args.save_sd = args.save_sd_screen
        args.png = True
        args.logs = True
        return command_screen(args)
    return 0


def command_touch(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    failures = 0

    if args.scene:
        code, _, body = dev.post("/api/touch", {"scene": args.scene})
        print_check("OK" if 200 <= code < 300 else "FAIL", f"POST /api/touch http={code}", short_json(body))
        failures += 0 if 200 <= code < 300 else 1
        time.sleep(args.wait)

    code, _, body = dev.get("/api/touch")
    print_check("OK" if code == 200 else "FAIL", f"GET /api/touch http={code}", short_json(body))
    failures += 0 if code == 200 else 1

    code, raw, _ = dev.get(f"/api/logs?tail={args.tail}")
    if code == 200:
        for line in [ln for ln in raw.splitlines() if "touch" in ln.lower()][-args.lines :]:
            print(line)
    else:
        print_check("WARN", f"/api/logs http={code}", raw[:300])

    if args.screen:
        args.save_sd = args.save_sd_screen
        args.png = True
        args.logs = True
        screen_result = command_screen(args)
        failures += 0 if screen_result == 0 else 1
    return 1 if failures else 0


def command_audio(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    deadline = time.time() + args.seconds
    samples: list[dict[str, Any]] = []
    while time.time() < deadline:
        try:
            code, _, body = dev.get("/api/audio/level")
            if code == 200 and isinstance(body, dict):
                samples.append(body)
                print_check("OK" if body.get("valid") else "WARN", "mic level",
                            f"rms={body.get('rms_db')} peak={body.get('peak_db')} valid={body.get('valid')}")
            else:
                print_check("FAIL", f"/api/audio/level http={code}", short_json(body))
        except Exception as exc:  # noqa: BLE001
            print_check("FAIL", "/api/audio/level", str(exc))
        time.sleep(args.interval)

    valid = [s for s in samples if s.get("valid")]
    if valid:
        rms_vals = [float(s.get("rms_db", -80.0)) for s in valid]
        peak_vals = [float(s.get("peak_db", -80.0)) for s in valid]
        print_check("OK", "mic summary",
                    f"samples={len(samples)} valid={len(valid)} rms_range={min(rms_vals):.1f}..{max(rms_vals):.1f} peak_max={max(peak_vals):.1f}")
    else:
        print_check("WARN", "mic summary", f"samples={len(samples)} valid=0")

    if args.speaker:
        cycle_args = argparse.Namespace(
            host=args.host,
            timeout=args.timeout,
            tail=args.tail,
            text=args.text,
            turn_wait=args.turn_wait,
            start_timeout=12.0,
            stop_timeout=12.0,
            report=args.report,
        )
        return command_gemini_cycle(cycle_args)
    return 0 if valid else 1


def command_watch(args: argparse.Namespace) -> int:
    dev = Device(args.host, args.timeout)
    last_logs = ""
    while True:
        snapshot = collect_snapshot(dev, args.tail)
        os.system("clear")
        failures = print_snapshot(snapshot)
        logs = str(snapshot.get("logs", {}).get("text", ""))
        if logs != last_logs:
            print("\n-- recent matching logs --")
            needles = ("gemini", "touch", "rwave", "audio", "ws", "setupComplete")
            for line in [ln for ln in logs.splitlines() if any(n in ln.lower() for n in needles)][-args.lines :]:
                print(line)
            last_logs = logs
        print(f"\nrefresh={args.interval}s failures={failures} ctrl-c to exit")
        time.sleep(args.interval)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--host",
        default=DEFAULT_HOST,
        help="device host or URL (or set JARVIS_DEVICE_HOST; v5 has no mDNS yet)",
    )
    parser.add_argument("--timeout", type=float, default=4.0, help="HTTP timeout seconds")
    parser.add_argument("--tail", type=int, default=65536, help="log tail bytes")
    sub = parser.add_subparsers(dest="command", required=True)

    def add_common(p: argparse.ArgumentParser) -> None:
        p.add_argument("--host", default=argparse.SUPPRESS, help="device host or URL")
        p.add_argument("--timeout", type=float, default=argparse.SUPPRESS, help="HTTP timeout seconds")
        p.add_argument("--tail", type=int, default=argparse.SUPPRESS, help="log tail bytes")

    p_status = sub.add_parser("status", help="probe health/status/audio/Gemini/touch/logs once")
    add_common(p_status)
    p_status.add_argument("--json", action="store_true", help="also print raw JSON snapshot")
    p_status.set_defaults(func=command_status)

    p_report = sub.add_parser("report", help="write a timestamped JSON diagnostic report")
    add_common(p_report)
    p_report.set_defaults(func=command_report)

    p_restart = sub.add_parser("restart", help="restart the device and wait for it to return")
    add_common(p_restart)
    p_restart.add_argument("--wait", type=float, default=45.0, help="seconds to wait for device return")
    p_restart.add_argument("--interval", type=float, default=1.0, help="poll interval seconds")
    p_restart.set_defaults(func=command_restart)

    p_screen = sub.add_parser("screen", help="fetch display snapshot JSON plus the PPM software mirror")
    add_common(p_screen)
    p_screen.add_argument("--save-sd", action="store_true", help="also save the PPM on the device SD card")
    p_screen.add_argument("--png", action="store_true", default=True, help="convert local PPM to PNG when possible")
    p_screen.add_argument("--no-png", dest="png", action="store_false", help="keep only the local PPM")
    p_screen.add_argument("--logs", action="store_true", default=True, help="classify device logs after capture")
    p_screen.add_argument("--no-logs", dest="logs", action="store_false", help="skip log classification")
    p_screen.set_defaults(func=command_screen)

    p_display_test = sub.add_parser(
        "display-test",
        help="set a deterministic panel test pattern (control-path evidence, not physical proof)",
    )
    add_common(p_display_test)
    p_display_test.add_argument(
        "pattern",
        choices=["off", "bars", "grid", "white", "red", "green", "blue"],
    )
    p_display_test.add_argument("--wait", type=float, default=0.0,
                                help="seconds to leave the pattern visible before capture/restore")
    p_display_test.add_argument("--screen", action="store_true",
                                help="also capture snapshot JSON and PPM after setting the pattern")
    p_display_test.add_argument("--restore", action="store_true",
                                help="restore the normal renderer after the optional wait/capture")
    p_display_test.set_defaults(func=command_display_test)

    p_face = sub.add_parser("face", help="force a display face state through HTTP")
    add_common(p_face)
    p_face.add_argument("state", choices=["off", "idle", "listen", "listening", "think", "thinking", "speak", "speaking"])
    p_face.add_argument("--amp", type=int, default=None, help="synthetic amplitude 0..1000 for listen/speak")
    p_face.add_argument("--screen", action="store_true", help="capture the screen after changing state")
    p_face.add_argument("--save-sd-screen", action="store_true", help="also save the captured screen to SD")
    p_face.set_defaults(func=command_face)

    p_touch = sub.add_parser("touch", help="read touch diagnostics or trigger a local scene")
    add_common(p_touch)
    p_touch.add_argument("scene", nargs="?", choices=["listen", "think", "speak", "showcase"],
                         help="optional local scene to trigger through /api/touch")
    p_touch.add_argument("--wait", type=float, default=1.0, help="seconds to wait after triggering a scene")
    p_touch.add_argument("--lines", type=int, default=80, help="touch log lines to print")
    p_touch.add_argument("--screen", action="store_true", help="capture the screen after touch action")
    p_touch.add_argument("--save-sd-screen", action="store_true", help="also save the captured screen to SD")
    p_touch.set_defaults(func=command_touch)

    p_audio = sub.add_parser("audio", help="sample mic levels and optionally exercise speaker via Gemini")
    add_common(p_audio)
    p_audio.add_argument("--seconds", type=float, default=5.0, help="mic sampling duration")
    p_audio.add_argument("--interval", type=float, default=0.5, help="mic sampling interval")
    p_audio.add_argument("--speaker", action="store_true", help="also run a Gemini text turn to exercise speaker path")
    p_audio.add_argument("--text", default="Say one short sentence.", help="text used for speaker path")
    p_audio.add_argument("--turn-wait", type=float, default=6.0, help="seconds to wait after text turn")
    p_audio.add_argument("--report", action="store_true", help="write a report after speaker cycle")
    p_audio.set_defaults(func=command_audio)

    p_audio_taps = sub.add_parser(
        "audio-taps",
        help="fetch audio tap metrics and PCM WAVs without starting a new test",
    )
    add_common(p_audio_taps)
    p_audio_taps.add_argument("--output", help="evidence directory (default: timestamped build log)")
    p_audio_taps.add_argument(
        "--source", nargs="+", choices=AUDIO_TAP_SOURCES, default=list(AUDIO_TAP_SOURCES),
        help="tap sources to download",
    )
    p_audio_taps.set_defaults(func=command_audio_taps)

    p_audio_self = sub.add_parser(
        "audio-self-test",
        help="start the bounded chirp/capture test, then fetch metrics and WAV taps",
    )
    add_common(p_audio_self)
    p_audio_self.add_argument("--wait", type=float, default=3.0,
                              help="seconds to wait for the bounded capture")
    p_audio_self.add_argument("--output", help="evidence directory (default: timestamped build log)")
    p_audio_self.add_argument(
        "--source", nargs="+", choices=AUDIO_TAP_SOURCES, default=list(AUDIO_TAP_SOURCES),
        help="tap sources to download",
    )
    p_audio_self.add_argument("--download", action="store_true", default=True,
                              help="download WAV taps after the test (default)")
    p_audio_self.add_argument("--no-download", dest="download", action="store_false",
                              help="fetch metrics only")
    p_audio_self.set_defaults(func=command_audio_self_test)

    p_evidence = sub.add_parser(
        "evidence",
        help="save a timestamped display/audio/status evidence bundle with proof boundaries",
    )
    add_common(p_evidence)
    p_evidence.add_argument("--output", help="bundle directory (default: timestamped build log)")
    p_evidence.add_argument(
        "--pattern", choices=["bars", "grid", "white", "red", "green", "blue"],
        help="request and capture a deterministic display pattern",
    )
    p_evidence.add_argument("--pattern-wait", type=float, default=2.0,
                            help="physical observation window before pattern capture")
    p_evidence.add_argument("--leave-pattern", action="store_true",
                            help="do not restore pattern=off after capture")
    p_evidence.add_argument("--audio-self-test", action="store_true",
                            help="start the chirp/capture test before collecting audio taps")
    p_evidence.add_argument("--audio-wait", type=float, default=3.0,
                            help="seconds to wait for the bounded audio capture")
    p_evidence.add_argument(
        "--source", nargs="+", choices=AUDIO_TAP_SOURCES, default=list(AUDIO_TAP_SOURCES),
        help="audio tap sources to download",
    )
    p_evidence.set_defaults(func=command_evidence)

    p_logs = sub.add_parser("logs", help="print recent device logs and classify known signatures")
    add_common(p_logs)
    p_logs.add_argument("--grep", default="", help="comma-separated case-insensitive filters")
    p_logs.add_argument("--lines", type=int, default=120, help="lines to print")
    p_logs.set_defaults(func=command_logs)

    p_cycle = sub.add_parser("gemini-cycle", help="start Gemini, optional text turn, stop, classify logs")
    add_common(p_cycle)
    p_cycle.add_argument("--text", default="Say one short sentence.", help="text turn to send; empty disables")
    p_cycle.add_argument("--turn-wait", type=float, default=6.0, help="seconds to wait after text turn")
    p_cycle.add_argument("--start-timeout", type=float, default=12.0, help="seconds to wait for active state")
    p_cycle.add_argument("--stop-timeout", type=float, default=12.0, help="seconds to wait for idle state")
    p_cycle.add_argument("--report", action="store_true", help="write a report after the cycle")
    p_cycle.set_defaults(func=command_gemini_cycle)

    p_watch = sub.add_parser("watch", help="refresh status and matching logs")
    add_common(p_watch)
    p_watch.add_argument("--interval", type=float, default=2.0, help="refresh interval seconds")
    p_watch.add_argument("--lines", type=int, default=40, help="recent matching log lines")
    p_watch.set_defaults(func=command_watch)

    return parser


def main(argv: list[str]) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not args.host:
        parser.error("set --host or JARVIS_DEVICE_HOST (v5 does not advertise mDNS yet)")
    try:
        return args.func(args)
    except KeyboardInterrupt:
        return 130
    except Exception as exc:  # noqa: BLE001 - diagnostics should fail loudly.
        print_check("FAIL", "diagnostic crashed", str(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
